// The served page: a minimal HTML shell around the stage-1 page bundle
// (three.js scene, see page/main.js). PAGE_JS is generated by esbuild.js and
// spliced in at runtime, so its content (backticks and all) never has to
// survive TS template-literal escaping.

import { PAGE_JS } from "./generated/pageBundle";

export function buildPage(): string {
  return (
    "<!doctype html>\n" +
    '<html lang="en">\n' +
    "<head>\n" +
    '<meta charset="utf-8" />\n' +
    '<meta name="viewport" content="width=device-width, initial-scale=1" />\n' +
    "<title>Chicken Coop</title>\n" +
    "<style>\n" +
    "  html, body { margin: 0; height: 100%; overflow: hidden; background: #87b5d8; }\n" +
    "  #stage { position: fixed; inset: 0; }\n" +
    "  #hud { position: fixed; top: 10px; left: 12px; padding: 6px 10px;\n" +
    "    background: rgba(255,255,255,0.82); border-radius: 8px;\n" +
    "    font: 13px/1.4 system-ui, sans-serif; color: #333; pointer-events: none; }\n" +
    "  #empty { position: fixed; inset: 0; display: none; align-items: center;\n" +
    "    justify-content: center; pointer-events: none;\n" +
    "    font: 15px system-ui, sans-serif; color: rgba(40,60,40,0.75); }\n" +
    "  #coop-mirror { display: none; }\n" +
    "</style>\n" +
    "</head>\n" +
    "<body>\n" +
    '<div id="stage"></div>\n' +
    '<div id="hud" data-testid="coop-hud"></div>\n' +
    '<div id="empty" data-testid="coop-empty">All hens are cooped up. Start a card to let one out.</div>\n' +
    '<div id="coop-mirror" data-testid="coop-mirror"></div>\n' +
    "<script>\n" +
    PAGE_JS +
    "\n</script>\n" +
    "</body>\n" +
    "</html>\n"
  );
}
